### ISSUE TITLE
Clicking on Dots

### ISSUE THREAD

**Issue by valeIT** [jeffaburt/UIPageViewController-Post#1]
Clicking on the dots though doesn't do anything though. 

Even when connecting the `UIPageControl` either from IB or from Code `addTarget` nothing fires. Any idea on how to make them clickable? 

Guess the child is getting the events, just the page control is added to the parent, so I can't delegate those back...?

**Comment by jeffaburt** [comment]
You are absolutely correct. Thanks for the great find! I fixed this in commit https://github.com/jeffaburt/UIPageViewController-Post/commit/94bec1e3d58c1f74401977ec57fbec68eb78cc3a.

PS: I used `addTarget`, and subscribed to the `ValueChanged` control event.
